### ISSUE TITLE
Add 'quota' definition

### ISSUE THREAD

**Issue by CosmicQ** [ibm-cloud-docs/vpc-on-classic#13]
It is unclear if a quota is a limit that could be adjusted or not.  It would be helpful to get a definition of the term in the doc.

For example:
```
Virtual Server Instances (VSIs) | 100 per account by default
```

This makes it sound like this is a limit that can be adjusted.  Others don't look like they can be adjusted though.

**Comment by lilorozco** [comment]
Thank you for your feedback. This is the only quota that can be increased by request through the support channels. I will make this clearer.

**Comment by lilorozco** [comment]
Updated topic: https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-quotas#vsi-quotas
