### ISSUE TITLE
Problem with comand: ibmcloud is target --gen 1

### ISSUE THREAD

**Issue by JoachimFischer** [ibm-cloud-docs/vpc-on-classic#14]
I try to submit the following comand    ibmcloud is target --gen 1  and got the message 'is' is not a valid parameter.

My CLI versions:    ibmcloud plugin list
Installierte Plug-ins auflisten...
Plug-in-Name                                       Version   
container-registry                                  0.1.426
container-service/kubernetes-service   0.4.3
dev                                                        2.4.0
sdk-gen                                                 0.1.12
cloud-functions/wsk/functions/fn        1.0.34

**Comment by lilorozco** [comment]
Hi. You need to install the vpc-infrastructure to get the `is` commands, run something like:

`ibmcloud plugin install vpc-infrastructure`
