### ISSUE TITLE
Update list of what is available to VPC on Classic via mirrors.adn.networklayer.com

### ISSUE THREAD

**Issue by jayhawk87** [ibm-cloud-docs/vpc-on-classic#18]
https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-service-endpoints-available-for-ibm-cloud-vpc shows that Ubuntu images are all that is available from mirrors.adn.networklayer.com

We know that Fedora and Debian packages are also available, but what else may be?

**Comment by austinmama** [comment]
@jayhawk87  Who should I follow up with so we capture all packages?

**Comment by austinmama** [comment]
Moving this comment to the staging server.  Please close issue here.

https://github.ibm.com/cloud-docs/vpc-on-classic/issues/483
